name: Build Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Get webhook version
        id: webhook
        run: |
          echo "version=$(< webhook.version)" >> $GITHUB_OUTPUT

      - name: Set Docker image metadata
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: library/webhook
          flavor: |
            latest=true
          tags: |
            ${{ steps.webhook.outputs.version }}
          labels: |
            org.opencontainers.image.version=${{ steps.webhook.outputs.version }}

      - name: Log in to Harbor Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: registry.moerman.online
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.HARBOR_REGISTRY }}/webhook/${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # - uses: actions/checkout@v3
      # - name: BuildAndPushImageOnHarbor
      #   run: |
      #     docker build ./ -t registry.moerman.online/library/info-site:${{ github.run_number }}
      #     docker push registry.moerman.online/library/info-site:${{ github.run_number }}
      
      ## https://github.com/docker/build-push-action/issues/252
      ## https://github.com/moby/buildkit/issues/1896
      ## Temporary fix
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache